import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import banner from '../images/banner.webp';
import logo from '../public/favicon.ico'
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';
import InstagramIcon from '@mui/icons-material/Instagram';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>PB Card Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=DotGothic16&family=Raleway:wght@100;200;300&display=swap" rel="stylesheet"/>
      </Head>
        <div className="main">
          <div className="header">
            <Image
              src={logo}
              alt="Logo image"
              width={125}
              height={125}
            />
            <ShoppingCartIcon fontSize="large"/>
          </div>
          <div className="navbar">
            <p>Home</p>
            <p>Products</p>
            <p>Register</p>
            <p>Policies</p>
          </div>
          <div className="banner">
            <Image
              src={banner}
              alt="Banner image"
              width="1000"
              height="500"
            />
          </div>
          <div className="greeting">
            <h1>
              Welcome to the world of Pokemon! My name is pa1ntbru5h! People call me pa1nt or PB! This world is inhabited by creatures called Pokemon!
            </h1>
          </div>
          <div className="footer">
            <a href = "mailto: pbcardshop@gmail.com">pbcardshop@gmail.com</a>
            <a href = "http://instagram.com/pbcardshop"><InstagramIcon className="igLogo"/></a>
            <p>&copy;2023 by PB Card Shop</p>
          </div>
        </div>
    </>
  )
}
